const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {hook,control,aliases}=require('../plugins/token-saver/scripts/token-saver.cjs');
function setup(){const cwd=fs.mkdtempSync(path.join(os.tmpdir(),'token-saver-'));return {cwd,event:{hook_event_name:'PostToolUse',tool_name:'Bash',cwd,tool_input:{command:'mvn test'},tool_response:{stdout:'Downloading dependency\n'.repeat(500)+'[ERROR] Expected 409 but was 200\nBUILD FAILURE',stderr:'',interrupted:false,isImage:false}}};}
test('inactive leaves original untouched',()=>{const {event}=setup();assert.equal(hook(event),null);});
test('activation is idempotent and compaction preserves failure and exact original',()=>{const {cwd,event}=setup();control('active',cwd);control('active',cwd);assert.equal(fs.readFileSync(path.join(cwd,'.gitignore'),'utf8').split('/.token-saver/').length,2);const result=hook(event);assert.match(result.hookSpecificOutput.updatedToolOutput.stdout,/Expected 409/);const names=fs.readdirSync(path.join(cwd,'.token-saver/logs'));const log=JSON.parse(fs.readFileSync(path.join(cwd,'.token-saver/logs',names[0])));assert.deepEqual(log.toolResponse,event.tool_response);assert.ok(log.compactChars<log.originalChars);assert.match(control('stats',cwd),/compactedCommands/);control('off',cwd);assert.equal(hook(event),null);});
test('protects diffs, JSON, images, malformed responses, interrupts and bypass',()=>{for(const mutate of [e=>e.tool_input.command='git diff',e=>e.tool_input.command='TOKEN_SAVER=off mvn test',e=>e.tool_response.isImage=true,e=>e.tool_response.interrupted=true,e=>delete e.tool_response.stderr,e=>e.tool_response.stdout=JSON.stringify({data:'x'.repeat(6000)})]){const {cwd,event}=setup();control('active',cwd);mutate(event);assert.equal(hook(event),null);}});
test('log write failure does not produce a replacement',()=>{const {cwd,event}=setup();control('active',cwd);fs.writeFileSync(path.join(cwd,'.token-saver/logs'),'blocked');assert.throws(()=>hook(event));});
test('aliases do not overwrite existing project commands',()=>{const {cwd}=setup();aliases(cwd);assert.ok(fs.existsSync(path.join(cwd,'.claude/commands/token-saver-active.md')));assert.throws(()=>aliases(cwd));});
test('generic tools retain significant middle error',()=>{const {cwd,event}=setup();control('active',cwd);event.tool_input.command='custom-build';event.tool_response.stdout='progress\n'.repeat(800)+'fatal: meaningful failure\n'+'progress\n'.repeat(800);assert.match(hook(event).hookSpecificOutput.updatedToolOutput.stdout,/meaningful failure/);});
